/**
 * CENTRAL GALLERY REGISTRY — the single editable source of truth for every
 * artwork shown in the Gallery. Edit `client`, `clientSlug`, `category`,
 * `title` or `featured` here and every surface updates.
 *
 * CLASSIFICATION POLICY: a client is recorded only when its name or logo is
 * clearly visible in the artwork and matches a known Diglizer engagement.
 * Anything unidentifiable is filed under "Diglizer Creative Work".
 */

export type GalleryCategory =
  | "social-media"
  | "campaigns"
  | "branding"
  | "print-packaging"
  | "websites-digital"
  | "reels-video";

export type GalleryMediaType = "image" | "video";

export interface GalleryItem {
  id: string;
  src: string;
  thumb: string;
  clientSlug: string;
  client: string;
  category: GalleryCategory;
  mediaType: GalleryMediaType;
  title: string;
  alt: string;
  width: number;
  height: number;
  ratio: string;
  featured: boolean;
  order: number;
  /** Vertical reel/video source. Only set when a real file exists. */
  videoSrc?: string;
}

export const galleryCategoryLabels: Record<GalleryCategory, string> = {
  "social-media": "Social Media",
  campaigns: "Campaigns",
  branding: "Branding",
  "print-packaging": "Print & Packaging",
  "websites-digital": "Websites & Digital",
  "reels-video": "Reels & Video",
};

export const galleryItems: GalleryItem[] = [
  {
    id: "pasbaan-e-adab-aisi-laagi-lagan-anup-jalota-concert-announcement",
    src: "/media/gallery/pasbaan-e-adab-aisi-laagi-lagan-anup-jalota-concert-announcement.webp",
    thumb: "/media/gallery/thumbs/pasbaan-e-adab-aisi-laagi-lagan-anup-jalota-concert-announcement.webp",
    clientSlug: "pasbaan-e-adab",
    client: "Pasbaan-e-Adab",
    category: "campaigns",
    mediaType: "image",
    title: "Aisi Laagi Lagan — Anup Jalota concert announcement",
    alt: "Aisi Laagi Lagan — Anup Jalota concert announcement designed by Diglizer Solution for Pasbaan-e-Adab",
    width: 1600,
    height: 900,
    ratio: "16:9",
    featured: true,
    order: 1,
  },
  {
    id: "mimas-world-hospitals-keep-your-digestive-tract-on-track-awareness-pos",
    src: "/media/gallery/mimas-world-hospitals-keep-your-digestive-tract-on-track-awareness-pos.webp",
    thumb: "/media/gallery/thumbs/mimas-world-hospitals-keep-your-digestive-tract-on-track-awareness-pos.webp",
    clientSlug: "mimas-world-hospitals",
    client: "MIMAS World Hospitals",
    category: "social-media",
    mediaType: "image",
    title: "Keep your digestive tract on track awareness post",
    alt: "Keep your digestive tract on track awareness post designed by Diglizer Solution for MIMAS World Hospitals",
    width: 1280,
    height: 1280,
    ratio: "1:1",
    featured: true,
    order: 2,
  },
  {
    id: "advaith-hospital-laser-and-laparoscopic-surgery-service-post",
    src: "/media/gallery/advaith-hospital-laser-and-laparoscopic-surgery-service-post.webp",
    thumb: "/media/gallery/thumbs/advaith-hospital-laser-and-laparoscopic-surgery-service-post.webp",
    clientSlug: "advaith-hospital",
    client: "Advaith Hospital",
    category: "social-media",
    mediaType: "image",
    title: "Laser and laparoscopic surgery service post",
    alt: "Laser and laparoscopic surgery service post designed by Diglizer Solution for Advaith Hospital",
    width: 1280,
    height: 1280,
    ratio: "1:1",
    featured: true,
    order: 3,
  },
  {
    id: "maharashtra-police-aaple-thane-surakshit-thane-seat-belt-safety-campai",
    src: "/media/gallery/maharashtra-police-aaple-thane-surakshit-thane-seat-belt-safety-campai.webp",
    thumb: "/media/gallery/thumbs/maharashtra-police-aaple-thane-surakshit-thane-seat-belt-safety-campai.webp",
    clientSlug: "maharashtra-police",
    client: "Maharashtra Police",
    category: "campaigns",
    mediaType: "image",
    title: "Aaple Thane Surakshit Thane seat belt safety campaign",
    alt: "Aaple Thane Surakshit Thane seat belt safety campaign designed by Diglizer Solution for Maharashtra Police",
    width: 1080,
    height: 1080,
    ratio: "1:1",
    featured: true,
    order: 4,
  },
  {
    id: "yashoda-ivf-intrauterine-insemination-explainer-post",
    src: "/media/gallery/yashoda-ivf-intrauterine-insemination-explainer-post.webp",
    thumb: "/media/gallery/thumbs/yashoda-ivf-intrauterine-insemination-explainer-post.webp",
    clientSlug: "yashoda-ivf",
    client: "Yashoda IVF & Fertility Centre",
    category: "social-media",
    mediaType: "image",
    title: "Intrauterine insemination explainer post",
    alt: "Intrauterine insemination explainer post designed by Diglizer Solution for Yashoda IVF & Fertility Centre",
    width: 1280,
    height: 1280,
    ratio: "1:1",
    featured: true,
    order: 5,
  },
  {
    id: "pasbaan-e-adab-mera-safar-with-sachin-pilgaonkar-event-design",
    src: "/media/gallery/pasbaan-e-adab-mera-safar-with-sachin-pilgaonkar-event-design.webp",
    thumb: "/media/gallery/thumbs/pasbaan-e-adab-mera-safar-with-sachin-pilgaonkar-event-design.webp",
    clientSlug: "pasbaan-e-adab",
    client: "Pasbaan-e-Adab",
    category: "campaigns",
    mediaType: "image",
    title: "Mera Safar with Sachin Pilgaonkar event design",
    alt: "Mera Safar with Sachin Pilgaonkar event design designed by Diglizer Solution for Pasbaan-e-Adab",
    width: 1600,
    height: 900,
    ratio: "16:9",
    featured: false,
    order: 6,
  },
  {
    id: "yashoda-ivf-hope-has-meaning-now-fertility-post",
    src: "/media/gallery/yashoda-ivf-hope-has-meaning-now-fertility-post.webp",
    thumb: "/media/gallery/thumbs/yashoda-ivf-hope-has-meaning-now-fertility-post.webp",
    clientSlug: "yashoda-ivf",
    client: "Yashoda IVF & Fertility Centre",
    category: "social-media",
    mediaType: "image",
    title: "Hope has meaning now fertility post",
    alt: "Hope has meaning now fertility post designed by Diglizer Solution for Yashoda IVF & Fertility Centre",
    width: 1280,
    height: 1280,
    ratio: "1:1",
    featured: false,
    order: 7,
  },
  {
    id: "pasbaan-e-adab-kailash-kher-birthday-tribute-design",
    src: "/media/gallery/pasbaan-e-adab-kailash-kher-birthday-tribute-design.webp",
    thumb: "/media/gallery/thumbs/pasbaan-e-adab-kailash-kher-birthday-tribute-design.webp",
    clientSlug: "pasbaan-e-adab",
    client: "Pasbaan-e-Adab",
    category: "campaigns",
    mediaType: "image",
    title: "Kailash Kher birthday tribute design",
    alt: "Kailash Kher birthday tribute design designed by Diglizer Solution for Pasbaan-e-Adab",
    width: 1000,
    height: 1000,
    ratio: "1:1",
    featured: false,
    order: 8,
  },
  {
    id: "mimas-world-hospitals-bone-weakening-and-osteoporosis-awareness-post",
    src: "/media/gallery/mimas-world-hospitals-bone-weakening-and-osteoporosis-awareness-post.webp",
    thumb: "/media/gallery/thumbs/mimas-world-hospitals-bone-weakening-and-osteoporosis-awareness-post.webp",
    clientSlug: "mimas-world-hospitals",
    client: "MIMAS World Hospitals",
    category: "social-media",
    mediaType: "image",
    title: "Bone weakening and osteoporosis awareness post",
    alt: "Bone weakening and osteoporosis awareness post designed by Diglizer Solution for MIMAS World Hospitals",
    width: 1280,
    height: 1280,
    ratio: "1:1",
    featured: false,
    order: 9,
  },
  {
    id: "pasbaan-e-adab-kavi-sammelan-with-dikshit-dankauri-announcement",
    src: "/media/gallery/pasbaan-e-adab-kavi-sammelan-with-dikshit-dankauri-announcement.webp",
    thumb: "/media/gallery/thumbs/pasbaan-e-adab-kavi-sammelan-with-dikshit-dankauri-announcement.webp",
    clientSlug: "pasbaan-e-adab",
    client: "Pasbaan-e-Adab",
    category: "campaigns",
    mediaType: "image",
    title: "Kavi Sammelan with Dikshit Dankauri announcement",
    alt: "Kavi Sammelan with Dikshit Dankauri announcement designed by Diglizer Solution for Pasbaan-e-Adab",
    width: 1600,
    height: 900,
    ratio: "16:9",
    featured: false,
    order: 10,
  },
  {
    id: "mimas-world-hospitals-advanced-medical-care-services-post",
    src: "/media/gallery/mimas-world-hospitals-advanced-medical-care-services-post.webp",
    thumb: "/media/gallery/thumbs/mimas-world-hospitals-advanced-medical-care-services-post.webp",
    clientSlug: "mimas-world-hospitals",
    client: "MIMAS World Hospitals",
    category: "social-media",
    mediaType: "image",
    title: "Advanced medical care services post",
    alt: "Advanced medical care services post designed by Diglizer Solution for MIMAS World Hospitals",
    width: 1280,
    height: 1280,
    ratio: "1:1",
    featured: false,
    order: 11,
  },
  {
    id: "yashoda-ivf-these-two-little-feet-parenthood-post",
    src: "/media/gallery/yashoda-ivf-these-two-little-feet-parenthood-post.webp",
    thumb: "/media/gallery/thumbs/yashoda-ivf-these-two-little-feet-parenthood-post.webp",
    clientSlug: "yashoda-ivf",
    client: "Yashoda IVF & Fertility Centre",
    category: "social-media",
    mediaType: "image",
    title: "These two little feet parenthood post",
    alt: "These two little feet parenthood post designed by Diglizer Solution for Yashoda IVF & Fertility Centre",
    width: 1280,
    height: 1280,
    ratio: "1:1",
    featured: false,
    order: 12,
  },
  {
    id: "maharashtra-police-navi-mumbai-police-do-not-drive-fast-road-safety-po",
    src: "/media/gallery/maharashtra-police-navi-mumbai-police-do-not-drive-fast-road-safety-po.webp",
    thumb: "/media/gallery/thumbs/maharashtra-police-navi-mumbai-police-do-not-drive-fast-road-safety-po.webp",
    clientSlug: "maharashtra-police",
    client: "Maharashtra Police",
    category: "campaigns",
    mediaType: "image",
    title: "Navi Mumbai Police do not drive fast road safety post",
    alt: "Navi Mumbai Police do not drive fast road safety post designed by Diglizer Solution for Maharashtra Police",
    width: 1080,
    height: 1080,
    ratio: "1:1",
    featured: false,
    order: 13,
  },
  {
    id: "mimas-world-hospitals-digestive-health-consultation-post",
    src: "/media/gallery/mimas-world-hospitals-digestive-health-consultation-post.webp",
    thumb: "/media/gallery/thumbs/mimas-world-hospitals-digestive-health-consultation-post.webp",
    clientSlug: "mimas-world-hospitals",
    client: "MIMAS World Hospitals",
    category: "social-media",
    mediaType: "image",
    title: "Digestive health consultation post",
    alt: "Digestive health consultation post designed by Diglizer Solution for MIMAS World Hospitals",
    width: 1280,
    height: 1280,
    ratio: "1:1",
    featured: false,
    order: 14,
  },
  {
    id: "aikaa-fashion-velvet-vibes-festive-handbag-product-design",
    src: "/media/gallery/aikaa-fashion-velvet-vibes-festive-handbag-product-design.webp",
    thumb: "/media/gallery/thumbs/aikaa-fashion-velvet-vibes-festive-handbag-product-design.webp",
    clientSlug: "aikaa-fashion",
    client: "Aikaa Fashion",
    category: "branding",
    mediaType: "image",
    title: "Velvet Vibes festive handbag product design",
    alt: "Velvet Vibes festive handbag product design designed by Diglizer Solution for Aikaa Fashion",
    width: 1440,
    height: 1796,
    ratio: "4:5",
    featured: true,
    order: 15,
  },
  {
    id: "pasbaan-e-adab-sheri-nashist-poetry-evening-announcement",
    src: "/media/gallery/pasbaan-e-adab-sheri-nashist-poetry-evening-announcement.webp",
    thumb: "/media/gallery/thumbs/pasbaan-e-adab-sheri-nashist-poetry-evening-announcement.webp",
    clientSlug: "pasbaan-e-adab",
    client: "Pasbaan-e-Adab",
    category: "campaigns",
    mediaType: "image",
    title: "Sheri Nashist poetry evening announcement",
    alt: "Sheri Nashist poetry evening announcement designed by Diglizer Solution for Pasbaan-e-Adab",
    width: 1080,
    height: 1080,
    ratio: "1:1",
    featured: false,
    order: 16,
  },
  {
    id: "pasbaan-e-adab-the-sunday-mushaira-with-javed-akhtar-design",
    src: "/media/gallery/pasbaan-e-adab-the-sunday-mushaira-with-javed-akhtar-design.webp",
    thumb: "/media/gallery/thumbs/pasbaan-e-adab-the-sunday-mushaira-with-javed-akhtar-design.webp",
    clientSlug: "pasbaan-e-adab",
    client: "Pasbaan-e-Adab",
    category: "campaigns",
    mediaType: "image",
    title: "The Sunday Mushaira with Javed Akhtar design",
    alt: "The Sunday Mushaira with Javed Akhtar design designed by Diglizer Solution for Pasbaan-e-Adab",
    width: 1600,
    height: 900,
    ratio: "16:9",
    featured: false,
    order: 17,
  },
  {
    id: "pasbaan-e-adab-ashok-chakradhar-poetry-feature-design",
    src: "/media/gallery/pasbaan-e-adab-ashok-chakradhar-poetry-feature-design.webp",
    thumb: "/media/gallery/thumbs/pasbaan-e-adab-ashok-chakradhar-poetry-feature-design.webp",
    clientSlug: "pasbaan-e-adab",
    client: "Pasbaan-e-Adab",
    category: "social-media",
    mediaType: "image",
    title: "Ashok Chakradhar poetry feature design",
    alt: "Ashok Chakradhar poetry feature design designed by Diglizer Solution for Pasbaan-e-Adab",
    width: 1080,
    height: 1080,
    ratio: "1:1",
    featured: false,
    order: 18,
  },
  {
    id: "pasbaan-e-adab-khud-ko-itana-bhi-mat-bachaya-kar-music-release-design",
    src: "/media/gallery/pasbaan-e-adab-khud-ko-itana-bhi-mat-bachaya-kar-music-release-design.webp",
    thumb: "/media/gallery/thumbs/pasbaan-e-adab-khud-ko-itana-bhi-mat-bachaya-kar-music-release-design.webp",
    clientSlug: "pasbaan-e-adab",
    client: "Pasbaan-e-Adab",
    category: "campaigns",
    mediaType: "image",
    title: "Khud Ko Itana Bhi Mat Bachaya Kar music release design",
    alt: "Khud Ko Itana Bhi Mat Bachaya Kar music release design designed by Diglizer Solution for Pasbaan-e-Adab",
    width: 1280,
    height: 720,
    ratio: "16:9",
    featured: false,
    order: 19,
  },
  {
    id: "aikaa-fashion-republic-day-handbag-collection-post",
    src: "/media/gallery/aikaa-fashion-republic-day-handbag-collection-post.webp",
    thumb: "/media/gallery/thumbs/aikaa-fashion-republic-day-handbag-collection-post.webp",
    clientSlug: "aikaa-fashion",
    client: "Aikaa Fashion",
    category: "branding",
    mediaType: "image",
    title: "Republic Day handbag collection post",
    alt: "Republic Day handbag collection post designed by Diglizer Solution for Aikaa Fashion",
    width: 1080,
    height: 1350,
    ratio: "4:5",
    featured: false,
    order: 20,
  },
  {
    id: "aikaa-fashion-elegance-product-range-campaign-visual",
    src: "/media/gallery/aikaa-fashion-elegance-product-range-campaign-visual.webp",
    thumb: "/media/gallery/thumbs/aikaa-fashion-elegance-product-range-campaign-visual.webp",
    clientSlug: "aikaa-fashion",
    client: "Aikaa Fashion",
    category: "branding",
    mediaType: "image",
    title: "Elegance product range campaign visual",
    alt: "Elegance product range campaign visual designed by Diglizer Solution for Aikaa Fashion",
    width: 1080,
    height: 1320,
    ratio: "4:5",
    featured: false,
    order: 21,
  },
  {
    id: "aikaa-fashion-the-festive-trio-product-launch-visual",
    src: "/media/gallery/aikaa-fashion-the-festive-trio-product-launch-visual.webp",
    thumb: "/media/gallery/thumbs/aikaa-fashion-the-festive-trio-product-launch-visual.webp",
    clientSlug: "aikaa-fashion",
    client: "Aikaa Fashion",
    category: "branding",
    mediaType: "image",
    title: "The Festive Trio product launch visual",
    alt: "The Festive Trio product launch visual designed by Diglizer Solution for Aikaa Fashion",
    width: 1080,
    height: 1320,
    ratio: "4:5",
    featured: false,
    order: 22,
  },
  {
    id: "suviksha-hospital-advanced-gynaecological-laparoscopic-services-post",
    src: "/media/gallery/suviksha-hospital-advanced-gynaecological-laparoscopic-services-post.webp",
    thumb: "/media/gallery/thumbs/suviksha-hospital-advanced-gynaecological-laparoscopic-services-post.webp",
    clientSlug: "suviksha-hospital",
    client: "Suviksha Hospital",
    category: "social-media",
    mediaType: "image",
    title: "Advanced gynaecological laparoscopic services post",
    alt: "Advanced gynaecological laparoscopic services post designed by Diglizer Solution for Suviksha Hospital",
    width: 1280,
    height: 1280,
    ratio: "1:1",
    featured: true,
    order: 23,
  },
  {
    id: "genetics-cryobank-every-father-s-journey-sperm-donor-campaign",
    src: "/media/gallery/genetics-cryobank-every-father-s-journey-sperm-donor-campaign.webp",
    thumb: "/media/gallery/thumbs/genetics-cryobank-every-father-s-journey-sperm-donor-campaign.webp",
    clientSlug: "genetics-cryobank",
    client: "Genetics Cryobank",
    category: "campaigns",
    mediaType: "image",
    title: "Every father's journey sperm donor campaign",
    alt: "Every father's journey sperm donor campaign designed by Diglizer Solution for Genetics Cryobank",
    width: 1080,
    height: 1350,
    ratio: "4:5",
    featured: true,
    order: 24,
  },
  {
    id: "genetics-cryobank-what-do-sperm-donors-get-explainer-post",
    src: "/media/gallery/genetics-cryobank-what-do-sperm-donors-get-explainer-post.webp",
    thumb: "/media/gallery/thumbs/genetics-cryobank-what-do-sperm-donors-get-explainer-post.webp",
    clientSlug: "genetics-cryobank",
    client: "Genetics Cryobank",
    category: "social-media",
    mediaType: "image",
    title: "What do sperm donors get explainer post",
    alt: "What do sperm donors get explainer post designed by Diglizer Solution for Genetics Cryobank",
    width: 1080,
    height: 1350,
    ratio: "4:5",
    featured: false,
    order: 25,
  },
  {
    id: "genetics-cryobank-ace-conference-agra-2026-exhibition-announcement",
    src: "/media/gallery/genetics-cryobank-ace-conference-agra-2026-exhibition-announcement.webp",
    thumb: "/media/gallery/thumbs/genetics-cryobank-ace-conference-agra-2026-exhibition-announcement.webp",
    clientSlug: "genetics-cryobank",
    client: "Genetics Cryobank",
    category: "campaigns",
    mediaType: "image",
    title: "ACE Conference Agra 2026 exhibition announcement",
    alt: "ACE Conference Agra 2026 exhibition announcement designed by Diglizer Solution for Genetics Cryobank",
    width: 1092,
    height: 1365,
    ratio: "4:5",
    featured: false,
    order: 26,
  },
  {
    id: "pasbaan-e-adab-remembering-amrita-pritam-birth-anniversary-design",
    src: "/media/gallery/pasbaan-e-adab-remembering-amrita-pritam-birth-anniversary-design.webp",
    thumb: "/media/gallery/thumbs/pasbaan-e-adab-remembering-amrita-pritam-birth-anniversary-design.webp",
    clientSlug: "pasbaan-e-adab",
    client: "Pasbaan-e-Adab",
    category: "campaigns",
    mediaType: "image",
    title: "Remembering Amrita Pritam birth anniversary design",
    alt: "Remembering Amrita Pritam birth anniversary design designed by Diglizer Solution for Pasbaan-e-Adab",
    width: 1080,
    height: 1080,
    ratio: "1:1",
    featured: false,
    order: 27,
  },
  {
    id: "yashoda-ivf-how-obesity-affects-fertility-explainer-post",
    src: "/media/gallery/yashoda-ivf-how-obesity-affects-fertility-explainer-post.webp",
    thumb: "/media/gallery/thumbs/yashoda-ivf-how-obesity-affects-fertility-explainer-post.webp",
    clientSlug: "yashoda-ivf",
    client: "Yashoda IVF & Fertility Centre",
    category: "social-media",
    mediaType: "image",
    title: "How obesity affects fertility explainer post",
    alt: "How obesity affects fertility explainer post designed by Diglizer Solution for Yashoda IVF & Fertility Centre",
    width: 1280,
    height: 1280,
    ratio: "1:1",
    featured: false,
    order: 28,
  },
  {
    id: "suviksha-hospital-safe-and-scar-free-laparoscopic-myomectomy-post",
    src: "/media/gallery/suviksha-hospital-safe-and-scar-free-laparoscopic-myomectomy-post.webp",
    thumb: "/media/gallery/thumbs/suviksha-hospital-safe-and-scar-free-laparoscopic-myomectomy-post.webp",
    clientSlug: "suviksha-hospital",
    client: "Suviksha Hospital",
    category: "social-media",
    mediaType: "image",
    title: "Safe and scar free laparoscopic myomectomy post",
    alt: "Safe and scar free laparoscopic myomectomy post designed by Diglizer Solution for Suviksha Hospital",
    width: 1080,
    height: 1080,
    ratio: "1:1",
    featured: false,
    order: 29,
  },
  {
    id: "maharashtra-police-navi-mumbai-police-triple-pillion-prohibited-campai",
    src: "/media/gallery/maharashtra-police-navi-mumbai-police-triple-pillion-prohibited-campai.webp",
    thumb: "/media/gallery/thumbs/maharashtra-police-navi-mumbai-police-triple-pillion-prohibited-campai.webp",
    clientSlug: "maharashtra-police",
    client: "Maharashtra Police",
    category: "campaigns",
    mediaType: "image",
    title: "Navi Mumbai Police triple pillion prohibited campaign",
    alt: "Navi Mumbai Police triple pillion prohibited campaign designed by Diglizer Solution for Maharashtra Police",
    width: 1080,
    height: 1080,
    ratio: "1:1",
    featured: false,
    order: 30,
  },
  {
    id: "genetics-cryobank-happy-ganesh-chaturthi-greeting-design",
    src: "/media/gallery/genetics-cryobank-happy-ganesh-chaturthi-greeting-design.webp",
    thumb: "/media/gallery/thumbs/genetics-cryobank-happy-ganesh-chaturthi-greeting-design.webp",
    clientSlug: "genetics-cryobank",
    client: "Genetics Cryobank",
    category: "social-media",
    mediaType: "image",
    title: "Happy Ganesh Chaturthi greeting design",
    alt: "Happy Ganesh Chaturthi greeting design designed by Diglizer Solution for Genetics Cryobank",
    width: 1080,
    height: 1350,
    ratio: "4:5",
    featured: false,
    order: 31,
  },
  {
    id: "yashoda-ivf-achieving-pregnancy-with-safety-post",
    src: "/media/gallery/yashoda-ivf-achieving-pregnancy-with-safety-post.webp",
    thumb: "/media/gallery/thumbs/yashoda-ivf-achieving-pregnancy-with-safety-post.webp",
    clientSlug: "yashoda-ivf",
    client: "Yashoda IVF & Fertility Centre",
    category: "social-media",
    mediaType: "image",
    title: "Achieving pregnancy with safety post",
    alt: "Achieving pregnancy with safety post designed by Diglizer Solution for Yashoda IVF & Fertility Centre",
    width: 1279,
    height: 1280,
    ratio: "1:1",
    featured: false,
    order: 32,
  },
  {
    id: "yashoda-ivf-where-your-parenthood-begins-post",
    src: "/media/gallery/yashoda-ivf-where-your-parenthood-begins-post.webp",
    thumb: "/media/gallery/thumbs/yashoda-ivf-where-your-parenthood-begins-post.webp",
    clientSlug: "yashoda-ivf",
    client: "Yashoda IVF & Fertility Centre",
    category: "social-media",
    mediaType: "image",
    title: "Where your parenthood begins post",
    alt: "Where your parenthood begins post designed by Diglizer Solution for Yashoda IVF & Fertility Centre",
    width: 1278,
    height: 1280,
    ratio: "1:1",
    featured: false,
    order: 33,
  },
  {
    id: "yashoda-ivf-come-as-a-couple-leave-as-a-family-post",
    src: "/media/gallery/yashoda-ivf-come-as-a-couple-leave-as-a-family-post.webp",
    thumb: "/media/gallery/thumbs/yashoda-ivf-come-as-a-couple-leave-as-a-family-post.webp",
    clientSlug: "yashoda-ivf",
    client: "Yashoda IVF & Fertility Centre",
    category: "social-media",
    mediaType: "image",
    title: "Come as a couple leave as a family post",
    alt: "Come as a couple leave as a family post designed by Diglizer Solution for Yashoda IVF & Fertility Centre",
    width: 1280,
    height: 1280,
    ratio: "1:1",
    featured: false,
    order: 34,
  },
  {
    id: "yashoda-ivf-who-needs-ivf-explainer-post",
    src: "/media/gallery/yashoda-ivf-who-needs-ivf-explainer-post.webp",
    thumb: "/media/gallery/thumbs/yashoda-ivf-who-needs-ivf-explainer-post.webp",
    clientSlug: "yashoda-ivf",
    client: "Yashoda IVF & Fertility Centre",
    category: "social-media",
    mediaType: "image",
    title: "Who needs IVF explainer post",
    alt: "Who needs IVF explainer post designed by Diglizer Solution for Yashoda IVF & Fertility Centre",
    width: 1280,
    height: 1280,
    ratio: "1:1",
    featured: false,
    order: 35,
  },
  {
    id: "yashoda-ivf-hope-can-turn-into-reality-post",
    src: "/media/gallery/yashoda-ivf-hope-can-turn-into-reality-post.webp",
    thumb: "/media/gallery/thumbs/yashoda-ivf-hope-can-turn-into-reality-post.webp",
    clientSlug: "yashoda-ivf",
    client: "Yashoda IVF & Fertility Centre",
    category: "social-media",
    mediaType: "image",
    title: "Hope can turn into reality post",
    alt: "Hope can turn into reality post designed by Diglizer Solution for Yashoda IVF & Fertility Centre",
    width: 1280,
    height: 1280,
    ratio: "1:1",
    featured: false,
    order: 36,
  },
  {
    id: "genetics-cryobank-is-sperm-donation-a-good-thing-illustrated-post",
    src: "/media/gallery/genetics-cryobank-is-sperm-donation-a-good-thing-illustrated-post.webp",
    thumb: "/media/gallery/thumbs/genetics-cryobank-is-sperm-donation-a-good-thing-illustrated-post.webp",
    clientSlug: "genetics-cryobank",
    client: "Genetics Cryobank",
    category: "social-media",
    mediaType: "image",
    title: "Is sperm donation a good thing illustrated post",
    alt: "Is sperm donation a good thing illustrated post designed by Diglizer Solution for Genetics Cryobank",
    width: 1080,
    height: 1350,
    ratio: "4:5",
    featured: false,
    order: 37,
  },
  {
    id: "yashoda-ivf-stand-by-her-she-is-on-ivf-post",
    src: "/media/gallery/yashoda-ivf-stand-by-her-she-is-on-ivf-post.webp",
    thumb: "/media/gallery/thumbs/yashoda-ivf-stand-by-her-she-is-on-ivf-post.webp",
    clientSlug: "yashoda-ivf",
    client: "Yashoda IVF & Fertility Centre",
    category: "social-media",
    mediaType: "image",
    title: "Stand by her she is on IVF post",
    alt: "Stand by her she is on IVF post designed by Diglizer Solution for Yashoda IVF & Fertility Centre",
    width: 1280,
    height: 1280,
    ratio: "1:1",
    featured: false,
    order: 38,
  },
  {
    id: "mimas-world-hospitals-advanced-laparoscopic-procedures-post",
    src: "/media/gallery/mimas-world-hospitals-advanced-laparoscopic-procedures-post.webp",
    thumb: "/media/gallery/thumbs/mimas-world-hospitals-advanced-laparoscopic-procedures-post.webp",
    clientSlug: "mimas-world-hospitals",
    client: "MIMAS World Hospitals",
    category: "social-media",
    mediaType: "image",
    title: "Advanced laparoscopic procedures post",
    alt: "Advanced laparoscopic procedures post designed by Diglizer Solution for MIMAS World Hospitals",
    width: 1080,
    height: 1080,
    ratio: "1:1",
    featured: false,
    order: 39,
  },
  {
    id: "maharashtra-police-thane-city-police-safe-eid-ride-helmet-campaign",
    src: "/media/gallery/maharashtra-police-thane-city-police-safe-eid-ride-helmet-campaign.webp",
    thumb: "/media/gallery/thumbs/maharashtra-police-thane-city-police-safe-eid-ride-helmet-campaign.webp",
    clientSlug: "maharashtra-police",
    client: "Maharashtra Police",
    category: "campaigns",
    mediaType: "image",
    title: "Thane City Police safe Eid ride helmet campaign",
    alt: "Thane City Police safe Eid ride helmet campaign designed by Diglizer Solution for Maharashtra Police",
    width: 1080,
    height: 1080,
    ratio: "1:1",
    featured: false,
    order: 40,
  },
  {
    id: "yashoda-ivf-unlock-your-path-to-parenthood-post",
    src: "/media/gallery/yashoda-ivf-unlock-your-path-to-parenthood-post.webp",
    thumb: "/media/gallery/thumbs/yashoda-ivf-unlock-your-path-to-parenthood-post.webp",
    clientSlug: "yashoda-ivf",
    client: "Yashoda IVF & Fertility Centre",
    category: "social-media",
    mediaType: "image",
    title: "Unlock your path to parenthood post",
    alt: "Unlock your path to parenthood post designed by Diglizer Solution for Yashoda IVF & Fertility Centre",
    width: 1280,
    height: 1280,
    ratio: "1:1",
    featured: false,
    order: 41,
  },
  {
    id: "pasbaan-e-adab-sudarshan-faakir-couplet-design",
    src: "/media/gallery/pasbaan-e-adab-sudarshan-faakir-couplet-design.webp",
    thumb: "/media/gallery/thumbs/pasbaan-e-adab-sudarshan-faakir-couplet-design.webp",
    clientSlug: "pasbaan-e-adab",
    client: "Pasbaan-e-Adab",
    category: "social-media",
    mediaType: "image",
    title: "Sudarshan Faakir couplet design",
    alt: "Sudarshan Faakir couplet design designed by Diglizer Solution for Pasbaan-e-Adab",
    width: 1080,
    height: 1080,
    ratio: "1:1",
    featured: false,
    order: 42,
  },
  {
    id: "pasbaan-e-adab-alvida-zakir-hussain-tribute-design",
    src: "/media/gallery/pasbaan-e-adab-alvida-zakir-hussain-tribute-design.webp",
    thumb: "/media/gallery/thumbs/pasbaan-e-adab-alvida-zakir-hussain-tribute-design.webp",
    clientSlug: "pasbaan-e-adab",
    client: "Pasbaan-e-Adab",
    category: "campaigns",
    mediaType: "image",
    title: "Alvida Zakir Hussain tribute design",
    alt: "Alvida Zakir Hussain tribute design designed by Diglizer Solution for Pasbaan-e-Adab",
    width: 1080,
    height: 1080,
    ratio: "1:1",
    featured: false,
    order: 43,
  },
  {
    id: "pasbaan-e-adab-the-mushaira-at-islam-gymkhana-announcement",
    src: "/media/gallery/pasbaan-e-adab-the-mushaira-at-islam-gymkhana-announcement.webp",
    thumb: "/media/gallery/thumbs/pasbaan-e-adab-the-mushaira-at-islam-gymkhana-announcement.webp",
    clientSlug: "pasbaan-e-adab",
    client: "Pasbaan-e-Adab",
    category: "campaigns",
    mediaType: "image",
    title: "The Mushaira at Islam Gymkhana announcement",
    alt: "The Mushaira at Islam Gymkhana announcement designed by Diglizer Solution for Pasbaan-e-Adab",
    width: 1080,
    height: 1080,
    ratio: "1:1",
    featured: false,
    order: 44,
  },
  {
    id: "pasbaan-e-adab-mohammad-alvi-couplet-design",
    src: "/media/gallery/pasbaan-e-adab-mohammad-alvi-couplet-design.webp",
    thumb: "/media/gallery/thumbs/pasbaan-e-adab-mohammad-alvi-couplet-design.webp",
    clientSlug: "pasbaan-e-adab",
    client: "Pasbaan-e-Adab",
    category: "social-media",
    mediaType: "image",
    title: "Mohammad Alvi couplet design",
    alt: "Mohammad Alvi couplet design designed by Diglizer Solution for Pasbaan-e-Adab",
    width: 1080,
    height: 1080,
    ratio: "1:1",
    featured: false,
    order: 45,
  },
  {
    id: "maharashtra-police-navi-mumbai-police-don-t-drink-and-drive-campaign",
    src: "/media/gallery/maharashtra-police-navi-mumbai-police-don-t-drink-and-drive-campaign.webp",
    thumb: "/media/gallery/thumbs/maharashtra-police-navi-mumbai-police-don-t-drink-and-drive-campaign.webp",
    clientSlug: "maharashtra-police",
    client: "Maharashtra Police",
    category: "campaigns",
    mediaType: "image",
    title: "Navi Mumbai Police don't drink and drive campaign",
    alt: "Navi Mumbai Police don't drink and drive campaign designed by Diglizer Solution for Maharashtra Police",
    width: 1080,
    height: 1080,
    ratio: "1:1",
    featured: false,
    order: 46,
  },
  {
    id: "advaith-hospital-types-of-fistula-explainer-post",
    src: "/media/gallery/advaith-hospital-types-of-fistula-explainer-post.webp",
    thumb: "/media/gallery/thumbs/advaith-hospital-types-of-fistula-explainer-post.webp",
    clientSlug: "advaith-hospital",
    client: "Advaith Hospital",
    category: "social-media",
    mediaType: "image",
    title: "Types of fistula explainer post",
    alt: "Types of fistula explainer post designed by Diglizer Solution for Advaith Hospital",
    width: 1280,
    height: 1280,
    ratio: "1:1",
    featured: false,
    order: 47,
  },
  {
    id: "yashoda-ivf-infertility-is-not-a-curse-post",
    src: "/media/gallery/yashoda-ivf-infertility-is-not-a-curse-post.webp",
    thumb: "/media/gallery/thumbs/yashoda-ivf-infertility-is-not-a-curse-post.webp",
    clientSlug: "yashoda-ivf",
    client: "Yashoda IVF & Fertility Centre",
    category: "social-media",
    mediaType: "image",
    title: "Infertility is not a curse post",
    alt: "Infertility is not a curse post designed by Diglizer Solution for Yashoda IVF & Fertility Centre",
    width: 1280,
    height: 1280,
    ratio: "1:1",
    featured: false,
    order: 48,
  },
  {
    id: "suviksha-hospital-why-choose-laparoscopic-surgery-explainer-post",
    src: "/media/gallery/suviksha-hospital-why-choose-laparoscopic-surgery-explainer-post.webp",
    thumb: "/media/gallery/thumbs/suviksha-hospital-why-choose-laparoscopic-surgery-explainer-post.webp",
    clientSlug: "suviksha-hospital",
    client: "Suviksha Hospital",
    category: "social-media",
    mediaType: "image",
    title: "Why choose laparoscopic surgery explainer post",
    alt: "Why choose laparoscopic surgery explainer post designed by Diglizer Solution for Suviksha Hospital",
    width: 1280,
    height: 1280,
    ratio: "1:1",
    featured: false,
    order: 49,
  },
  {
    id: "pasbaan-e-adab-quaiser-khalid-ips-poetry-feature-design",
    src: "/media/gallery/pasbaan-e-adab-quaiser-khalid-ips-poetry-feature-design.webp",
    thumb: "/media/gallery/thumbs/pasbaan-e-adab-quaiser-khalid-ips-poetry-feature-design.webp",
    clientSlug: "pasbaan-e-adab",
    client: "Pasbaan-e-Adab",
    category: "campaigns",
    mediaType: "image",
    title: "Quaiser Khalid IPS poetry feature design",
    alt: "Quaiser Khalid IPS poetry feature design designed by Diglizer Solution for Pasbaan-e-Adab",
    width: 1600,
    height: 900,
    ratio: "16:9",
    featured: false,
    order: 50,
  },
  {
    id: "pasbaan-e-adab-basheer-badr-couplet-design",
    src: "/media/gallery/pasbaan-e-adab-basheer-badr-couplet-design.webp",
    thumb: "/media/gallery/thumbs/pasbaan-e-adab-basheer-badr-couplet-design.webp",
    clientSlug: "pasbaan-e-adab",
    client: "Pasbaan-e-Adab",
    category: "social-media",
    mediaType: "image",
    title: "Basheer Badr couplet design",
    alt: "Basheer Badr couplet design designed by Diglizer Solution for Pasbaan-e-Adab",
    width: 1080,
    height: 1080,
    ratio: "1:1",
    featured: false,
    order: 51,
  },
  {
    id: "mimas-world-hospitals-weak-urinary-stream-prostate-awareness-post",
    src: "/media/gallery/mimas-world-hospitals-weak-urinary-stream-prostate-awareness-post.webp",
    thumb: "/media/gallery/thumbs/mimas-world-hospitals-weak-urinary-stream-prostate-awareness-post.webp",
    clientSlug: "mimas-world-hospitals",
    client: "MIMAS World Hospitals",
    category: "social-media",
    mediaType: "image",
    title: "Weak urinary stream prostate awareness post",
    alt: "Weak urinary stream prostate awareness post designed by Diglizer Solution for MIMAS World Hospitals",
    width: 1280,
    height: 1280,
    ratio: "1:1",
    featured: false,
    order: 52,
  },
  {
    id: "suviksha-hospital-laparoscopic-surgery-recovery-post",
    src: "/media/gallery/suviksha-hospital-laparoscopic-surgery-recovery-post.webp",
    thumb: "/media/gallery/thumbs/suviksha-hospital-laparoscopic-surgery-recovery-post.webp",
    clientSlug: "suviksha-hospital",
    client: "Suviksha Hospital",
    category: "social-media",
    mediaType: "image",
    title: "Laparoscopic surgery recovery post",
    alt: "Laparoscopic surgery recovery post designed by Diglizer Solution for Suviksha Hospital",
    width: 1280,
    height: 1280,
    ratio: "1:1",
    featured: false,
    order: 53,
  },
  {
    id: "yashoda-ivf-the-infertility-puzzle-lifestyle-post",
    src: "/media/gallery/yashoda-ivf-the-infertility-puzzle-lifestyle-post.webp",
    thumb: "/media/gallery/thumbs/yashoda-ivf-the-infertility-puzzle-lifestyle-post.webp",
    clientSlug: "yashoda-ivf",
    client: "Yashoda IVF & Fertility Centre",
    category: "social-media",
    mediaType: "image",
    title: "The infertility puzzle lifestyle post",
    alt: "The infertility puzzle lifestyle post designed by Diglizer Solution for Yashoda IVF & Fertility Centre",
    width: 1280,
    height: 1280,
    ratio: "1:1",
    featured: false,
    order: 54,
  },
  {
    id: "pasbaan-e-adab-naseeruddin-shah-birthday-tribute-design",
    src: "/media/gallery/pasbaan-e-adab-naseeruddin-shah-birthday-tribute-design.webp",
    thumb: "/media/gallery/thumbs/pasbaan-e-adab-naseeruddin-shah-birthday-tribute-design.webp",
    clientSlug: "pasbaan-e-adab",
    client: "Pasbaan-e-Adab",
    category: "campaigns",
    mediaType: "image",
    title: "Naseeruddin Shah birthday tribute design",
    alt: "Naseeruddin Shah birthday tribute design designed by Diglizer Solution for Pasbaan-e-Adab",
    width: 1000,
    height: 1000,
    ratio: "1:1",
    featured: false,
    order: 55,
  },
  {
    id: "xpert-super-speciality-trulife-trulife-fertility-free-fertility-camp-a",
    src: "/media/gallery/xpert-super-speciality-trulife-trulife-fertility-free-fertility-camp-a.webp",
    thumb: "/media/gallery/thumbs/xpert-super-speciality-trulife-trulife-fertility-free-fertility-camp-a.webp",
    clientSlug: "xpert-super-speciality-trulife",
    client: "Xpert Super Speciality Trulife",
    category: "campaigns",
    mediaType: "image",
    title: "Trulife Fertility free fertility camp announcement",
    alt: "Trulife Fertility free fertility camp announcement designed by Diglizer Solution for Xpert Super Speciality Trulife",
    width: 1280,
    height: 1280,
    ratio: "1:1",
    featured: false,
    order: 56,
  },
  {
    id: "pasbaan-e-adab-amu-tarana-by-majaz-lakhnawi-feature-design",
    src: "/media/gallery/pasbaan-e-adab-amu-tarana-by-majaz-lakhnawi-feature-design.webp",
    thumb: "/media/gallery/thumbs/pasbaan-e-adab-amu-tarana-by-majaz-lakhnawi-feature-design.webp",
    clientSlug: "pasbaan-e-adab",
    client: "Pasbaan-e-Adab",
    category: "campaigns",
    mediaType: "image",
    title: "Amu Tarana by Majaz Lakhnawi feature design",
    alt: "Amu Tarana by Majaz Lakhnawi feature design designed by Diglizer Solution for Pasbaan-e-Adab",
    width: 1600,
    height: 900,
    ratio: "16:9",
    featured: false,
    order: 57,
  },
  {
    id: "yashoda-ivf-who-needs-iui-treatment-explainer-post",
    src: "/media/gallery/yashoda-ivf-who-needs-iui-treatment-explainer-post.webp",
    thumb: "/media/gallery/thumbs/yashoda-ivf-who-needs-iui-treatment-explainer-post.webp",
    clientSlug: "yashoda-ivf",
    client: "Yashoda IVF & Fertility Centre",
    category: "social-media",
    mediaType: "image",
    title: "Who needs IUI treatment explainer post",
    alt: "Who needs IUI treatment explainer post designed by Diglizer Solution for Yashoda IVF & Fertility Centre",
    width: 1280,
    height: 1280,
    ratio: "1:1",
    featured: false,
    order: 58,
  },
  {
    id: "yashoda-ivf-motherhood-completes-womanhood-post",
    src: "/media/gallery/yashoda-ivf-motherhood-completes-womanhood-post.webp",
    thumb: "/media/gallery/thumbs/yashoda-ivf-motherhood-completes-womanhood-post.webp",
    clientSlug: "yashoda-ivf",
    client: "Yashoda IVF & Fertility Centre",
    category: "social-media",
    mediaType: "image",
    title: "Motherhood completes womanhood post",
    alt: "Motherhood completes womanhood post designed by Diglizer Solution for Yashoda IVF & Fertility Centre",
    width: 1280,
    height: 1280,
    ratio: "1:1",
    featured: false,
    order: 59,
  },
  {
    id: "advaith-hospital-ignoring-the-urge-gut-health-awareness-post",
    src: "/media/gallery/advaith-hospital-ignoring-the-urge-gut-health-awareness-post.webp",
    thumb: "/media/gallery/thumbs/advaith-hospital-ignoring-the-urge-gut-health-awareness-post.webp",
    clientSlug: "advaith-hospital",
    client: "Advaith Hospital",
    category: "social-media",
    mediaType: "image",
    title: "Ignoring the urge gut health awareness post",
    alt: "Ignoring the urge gut health awareness post designed by Diglizer Solution for Advaith Hospital",
    width: 1280,
    height: 1280,
    ratio: "1:1",
    featured: false,
    order: 60,
  },
  {
    id: "advaith-hospital-laparoscopic-hernia-surgery-offer-post",
    src: "/media/gallery/advaith-hospital-laparoscopic-hernia-surgery-offer-post.webp",
    thumb: "/media/gallery/thumbs/advaith-hospital-laparoscopic-hernia-surgery-offer-post.webp",
    clientSlug: "advaith-hospital",
    client: "Advaith Hospital",
    category: "social-media",
    mediaType: "image",
    title: "Laparoscopic hernia surgery offer post",
    alt: "Laparoscopic hernia surgery offer post designed by Diglizer Solution for Advaith Hospital",
    width: 1080,
    height: 1080,
    ratio: "1:1",
    featured: false,
    order: 61,
  },
  {
    id: "pasbaan-e-adab-sahir-ludhianvi-couplet-design",
    src: "/media/gallery/pasbaan-e-adab-sahir-ludhianvi-couplet-design.webp",
    thumb: "/media/gallery/thumbs/pasbaan-e-adab-sahir-ludhianvi-couplet-design.webp",
    clientSlug: "pasbaan-e-adab",
    client: "Pasbaan-e-Adab",
    category: "social-media",
    mediaType: "image",
    title: "Sahir Ludhianvi couplet design",
    alt: "Sahir Ludhianvi couplet design designed by Diglizer Solution for Pasbaan-e-Adab",
    width: 1080,
    height: 1080,
    ratio: "1:1",
    featured: false,
    order: 62,
  },
  {
    id: "pasbaan-e-adab-hoton-se-chulo-tum-music-feature-design",
    src: "/media/gallery/pasbaan-e-adab-hoton-se-chulo-tum-music-feature-design.webp",
    thumb: "/media/gallery/thumbs/pasbaan-e-adab-hoton-se-chulo-tum-music-feature-design.webp",
    clientSlug: "pasbaan-e-adab",
    client: "Pasbaan-e-Adab",
    category: "campaigns",
    mediaType: "image",
    title: "Hoton Se Chulo Tum music feature design",
    alt: "Hoton Se Chulo Tum music feature design designed by Diglizer Solution for Pasbaan-e-Adab",
    width: 1280,
    height: 720,
    ratio: "16:9",
    featured: false,
    order: 63,
  },
  {
    id: "mimas-world-hospitals-signs-to-consult-a-urology-expert-post",
    src: "/media/gallery/mimas-world-hospitals-signs-to-consult-a-urology-expert-post.webp",
    thumb: "/media/gallery/thumbs/mimas-world-hospitals-signs-to-consult-a-urology-expert-post.webp",
    clientSlug: "mimas-world-hospitals",
    client: "MIMAS World Hospitals",
    category: "social-media",
    mediaType: "image",
    title: "Signs to consult a urology expert post",
    alt: "Signs to consult a urology expert post designed by Diglizer Solution for MIMAS World Hospitals",
    width: 1000,
    height: 1000,
    ratio: "1:1",
    featured: false,
    order: 64,
  },
  {
    id: "genetics-cryobank-oligospermia-low-sperm-count-explainer-post",
    src: "/media/gallery/genetics-cryobank-oligospermia-low-sperm-count-explainer-post.webp",
    thumb: "/media/gallery/thumbs/genetics-cryobank-oligospermia-low-sperm-count-explainer-post.webp",
    clientSlug: "genetics-cryobank",
    client: "Genetics Cryobank",
    category: "social-media",
    mediaType: "image",
    title: "Oligospermia low sperm count explainer post",
    alt: "Oligospermia low sperm count explainer post designed by Diglizer Solution for Genetics Cryobank",
    width: 1080,
    height: 1350,
    ratio: "4:5",
    featured: false,
    order: 65,
  },
  {
    id: "genetics-cryobank-healthy-sperm-count-motility-and-shape-infographic",
    src: "/media/gallery/genetics-cryobank-healthy-sperm-count-motility-and-shape-infographic.webp",
    thumb: "/media/gallery/thumbs/genetics-cryobank-healthy-sperm-count-motility-and-shape-infographic.webp",
    clientSlug: "genetics-cryobank",
    client: "Genetics Cryobank",
    category: "social-media",
    mediaType: "image",
    title: "Healthy sperm count motility and shape infographic",
    alt: "Healthy sperm count motility and shape infographic designed by Diglizer Solution for Genetics Cryobank",
    width: 1080,
    height: 1350,
    ratio: "4:5",
    featured: false,
    order: 66,
  },
];

/** Categories that actually contain work — empty filters are never shown. */
export const activeGalleryCategories = (
  Object.keys(galleryCategoryLabels) as GalleryCategory[]
).filter((c) => galleryItems.some((i) => i.category === c));

export const galleryByCategory = (c: GalleryCategory) =>
  galleryItems.filter((i) => i.category === c);

export const galleryForClient = (slug: string) =>
  galleryItems.filter((i) => i.clientSlug === slug);

export const featuredGallery = galleryItems.filter((i) => i.featured);

export const galleryClients = Array.from(
  new Map(galleryItems.map((i) => [i.clientSlug, i.client])).entries(),
).map(([slug, name]) => ({ slug, name }));
